#!/usr/bin/env node
// review.js
// Entry point for the Salesforce PR review bot. Orchestrates:
//   Layer 1 — static rules (rules/*)
//   Layer 2 — Claude AI review (ai-review.js)
// Merges findings, posts a single GitHub review with inline comments.

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const { Octokit } = require('@octokit/rest');
const { parseUnifiedDiff } = require('./utils/diffParser');
const { runAiReview } = require('./ai-review');

const apexRules = require('./rules/apex');
const triggerRules = require('./rules/trigger');
const lwcRules = require('./rules/lwc');
const securityRules = require('./rules/security');
const metadataRules = require('./rules/metadata');

const REPO_ROOT = process.cwd();

function getDiff() {
  const base = process.env.BASE_SHA;
  const head = process.env.HEAD_SHA;
  return execSync(`git diff --unified=3 ${base} ${head}`, { encoding: 'utf8', maxBuffer: 50 * 1024 * 1024 });
}

function safeRead(p) {
  try { return fs.readFileSync(p, 'utf8'); } catch { return ''; }
}

async function runStaticLayer(changedFiles) {
  const findings = [];
  for (const f of changedFiles) {
    if (f.deleted) {
      findings.push(...metadataRules.checkDeleted(f.path));
      continue;
    }
    const content = safeRead(path.join(REPO_ROOT, f.path));
    if (!content) continue;
    findings.push(...apexRules.check(f.path, content));
    findings.push(...triggerRules.check(f.path, content));
    findings.push(...lwcRules.check(f.path, content));
    findings.push(...securityRules.check(f.path, content));
    findings.push(...metadataRules.check(f.path, content));
  }
  return findings;
}

async function postReview({ owner, repo, prNumber, findings, changedFiles, aiError, prAuthor }) {
  const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
  const mention = prAuthor ? `@${prAuthor} ` : '';

  if (findings.length === 0) {
    const body = aiError
      ? `${mention}⚠️ **Salesforce PR Review** — No issues found by the static layer. **The AI review layer failed to run** (${aiError}) — this review is incomplete, not clean.`
      : '✅ **Salesforce PR Review** — No issues found by static or AI layers.';
    await octokit.pulls.createReview({
      owner, repo, pull_number: prNumber,
      body,
      event: 'COMMENT',
    });
    return;
  }

  // Build inline comments only on lines that the PR actually changed
  const changedLineMap = new Map();
  for (const f of changedFiles) {
    changedLineMap.set(f.path, new Set(f.changedLines));
  }

  const inlineComments = [];
  const tableRows = [];
  for (const finding of findings) {
    const sevEmoji = finding.severity === 'high' ? '🔴' : finding.severity === 'medium' ? '🟡' : '🔵';
    const fullMessage = `${sevEmoji} **${finding.ruleId}** — ${finding.message}${finding.suggestion ? `\n\n_Suggested fix:_ ${finding.suggestion}` : ''}`;

    const fileLines = changedLineMap.get(finding.path);
    if (fileLines && fileLines.has(finding.startLine)) {
      inlineComments.push({
        path: finding.path,
        line: finding.startLine,
        body: fullMessage,
      });
    } else {
      // Out-of-diff finding — append to summary table
      const suggestion = finding.suggestion ? finding.suggestion.replace(/\|/g, '\\|') : '—';
      tableRows.push(`| ${sevEmoji} ${finding.severity} | ${finding.ruleId} | \`${finding.path}:${finding.startLine}\` | ${finding.message.replace(/\|/g, '\\|')} | ${suggestion} |`);
    }
  }

  const aiFindings = findings.filter(f => f.ruleId.startsWith('SF-AI-')).length;
  const staticFindings = findings.length - aiFindings;

  // Blocking severities request changes; 'low' stays advisory (COMMENT only).
  const hasBlocking = findings.some(f => f.severity === 'high' || f.severity === 'medium');

  const body = [
    `${mention}## Salesforce PR Review`,
    '',
    `Found **${findings.length}** issue(s): ${staticFindings} from static rules, ${aiFindings} from AI layer.`,
    hasBlocking ? '**Changes requested** — please address the findings below before merging.' : '',
    '',
    tableRows.length > 0 ? '### Findings outside the diff\n\n| Severity | Rule | Location | Message | Suggested fix |\n|---|---|---|---|---|\n' + tableRows.join('\n') : '',
    '',
    '---',
    '',
    aiError
      ? `⚠️ _The AI review layer failed to run (${aiError}) — findings below are from the static layer only._`
      : aiFindings > 0
        ? '_AI findings (`SF-AI-*`) generated by Claude Sonnet — read-only review layer._'
        : '_All findings from static rules. AI layer was skipped or found no issues._',
  ].filter(Boolean).join('\n');

  await octokit.pulls.createReview({
    owner, repo, pull_number: prNumber,
    body,
    event: hasBlocking ? 'REQUEST_CHANGES' : 'COMMENT',
    comments: inlineComments,
  });
}

async function main() {
  const owner = process.env.REPO_OWNER;
  const repo = process.env.REPO_NAME;
  const prNumber = parseInt(process.env.PR_NUMBER, 10);
  const prAuthor = process.env.PR_AUTHOR || null;

  console.log(`Reviewing PR #${prNumber} on ${owner}/${repo}`);

  const diff = getDiff();
  const changedFiles = parseUnifiedDiff(diff);
  console.log(`Changed files: ${changedFiles.length}`);

  // Layer 1
  const staticFindings = await runStaticLayer(changedFiles);
  console.log(`Static rules: ${staticFindings.length} finding(s)`);

  // Layer 2
  const { findings: aiFindings, error: aiError } = await runAiReview({ changedFiles, repoRoot: REPO_ROOT });
  console.log(`AI layer: ${aiFindings.length} finding(s)${aiError ? ` (error: ${aiError})` : ''}`);

  const allFindings = [...staticFindings, ...aiFindings];

  // Sort: high severity first, then by file/line
  const sevOrder = { high: 0, medium: 1, low: 2 };
  allFindings.sort((a, b) => {
    if (sevOrder[a.severity] !== sevOrder[b.severity]) return sevOrder[a.severity] - sevOrder[b.severity];
    if (a.path !== b.path) return a.path.localeCompare(b.path);
    return a.startLine - b.startLine;
  });

  await postReview({ owner, repo, prNumber, findings: allFindings, changedFiles, aiError, prAuthor });
  console.log('Review posted.');
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
